### ISSUE TITLE
New Tagged Release

### ISSUE THREAD

**Issue by davidrajones** [paulhager/smart-phase#11]
Hi there, 

Would it be possible to have a tagged release of smart-phase as it is at the moment please, or is tehre one planned in the very near future? 
We're looking to make a Docker image including smart-phase so linking to a specific release would be preferable to download so the version doesn't have the potential to change under our feet when building.

Regards,

David

**Comment by paulhager** [comment]
Sure, just made a 1.2.0 release of the current state.
