### ISSUE TITLE
Error when running in trio mode

### ISSUE THREAD

**Issue by Madelinehazel** [paulhager/smart-phase#3]
Hello, 

I am trying to run smart-phase in explorative mode for a trio. My script is below:
`java -jar ~/tools/smart-phase/smartPhase.jar \
-g ~/tools/smart-phase/BED/allGeneRegionsCanonical.HG19.GRCh37.bed \
-a 489.vcf.gz \
-p 489_TR0011  \
-r 489_TR0011.bam \
-m 30 \
-d 489.ped -o 489_output.tsv -x -t -vcf -c 0.1`

And I get this error: 

`------------------
INTERVAL CONTIG: 1
INTERVAL START: 58946390
INTERVAL END: 59012446
Filtered Variants found in interval: 2
Exception in thread "main" java.lang.NullPointerException
	at smartPhase.SmartPhase.trioPhase(SmartPhase.java:1998)
	at smartPhase.SmartPhase.main(SmartPhase.java:651)`

When I remove the -t flag (i.e. I don't run in trio mode), I don't get errors. I'm not sure why it doesn't work in trio mode. Help would be appreciated!

**Comment by timjeske** [comment]
Dear Madeline Couse, 

thank you for using SmartPhase. 

According to the error message, the genotype of the mother of 489_TR0011 cannot be found in the VCF file. The reason might either be different IDs of the mother in 489.ped and 489.vcf.gz or the genotypes of the mother are completely missing in VCF files. Please note, the genotypes of both parents are required to perform trio-phasing.

In the case, this does not solve the error please send us your PED file and a subset of your VCF file to check what is going wrong. 

I will close this issue for new but please don't hesitate to reopen it if you have further questions.

Kind regards
Tim Jeske
