### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by jielab** [paulhager/smart-phase#5]
Hi, there:

Please refer to the screenshot below. I got an error message like this. 
Can you please kindly let me know what I might have done wrong?

![111](https://user-images.githubusercontent.com/26947455/95280242-23d99000-0887-11eb-9443-06d1569c4461.JPG)

Also, do I must use the "-a XXX.vcf" option to specify which variants to phase? How about if I use the "-g file.bed" option instead?

Thank you & best regards,
Jie

**Comment by timjeske** [comment]
Dear Jie, 

the error message comes from the fact that you have not specified a PED file although you want to use trio-phasing (option -t).
So, either specify a PED file defining the parent-child relationship or don't use the -t option if you don't have parent sequencing data available, which is the case as you have just one sample in your `$id.vcf`.

The -a option is used to specify the set of all variants that SmartPhase uses to phase either all variants in the regions specified in the BED file (-g), or all variants in a filtered VCF file or all pairs of variants in a TSV file (-f).

Please also refer to [the documention of the options](https://github.com/paulhager/smart-phase#options) for more detailed explanations. 

Kind regards
Tim

**Comment by jielab** [comment]
Dear Tim:

Sorry, my bad. Yes, I should have removed "-t". Now it works. 

However, please see the screenshot below. Since my input .vcf.gz file only has two variants on Chr19, was that the reason why Smart-Phase keeps saying "intervals skipped ..."?

![捕获](https://user-images.githubusercontent.com/26947455/95321465-a8e79800-08cd-11eb-81a5-dc32168c1018.JPG)

Why the output $id.tsv file does not contain any phased haplotypes?

Best regards,
jie

**Comment by jielab** [comment]
Dear Tim:

Sorry, my bad. Yes, I should have removed "-t". Now it works.

However, please see the screenshot below. Since my input .vcf.gz file only has two variants on Chr19, was that the reason why Smart-Phase keeps saying "intervals skipped ..."?

Why the output $id.tsv file does not contain any phased haplotypes?

I just wrote the above on Github, but the attached image does not show up. So, I am writing via email again.

Best regards,
jie

 

 

发件人: timjeske <notifications@github.com> 
发送时间: 2020年10月7日 14:48
收件人: paulhager/smart-phase <smart-phase@noreply.github.com>
抄送: Jie Huang <jiehuang001@gmail.com>; Author <author@noreply.github.com>
主题: Re: [paulhager/smart-phase] Exception in thread "main" java.lang.NullPointerException (#5)

 

Dear Jie,

the error message comes from the fact that you have not specified a PED file although you want to use trio-phasing (option -t).
So, either specify a PED file defining the parent-child relationship or don't use the -t option if you don't have parent sequencing data available, which is the case as you have just one sample in your $id.vcf.

The -a option is used to specify the set of all variants that SmartPhase uses to phase either all variants in the regions specified in the BED file (-g), or all variants in a filtered VCF file or all pairs of variants in a TSV file (-f).

Please also refer to the documention of the options <https://github.com/paulhager/smart-phase#options>  for more detailed explanations.

Kind regards
Tim

**Comment by paulhager** [comment]
Hi Jie,

Using the data you uploaded in the other issue, which seems to be identical to this case, it works on my end. Can you double check the all.bed file to make sure that the pair you are phasing is within the ranges specified? As stated in the output of smart phase, your bed file is specifying regions to phase on all chromosomes. But SmartPhase only found variants in the vcf for contig 19. So far all other contigs he says they are “not important” because the id was not in the vcf.

Using a bam file that only has chromosome 19 phases normally (see attached screenshot).

Best,
Paul
